### ISSUE TITLE
Clarify <Le disque plane. Mon adversaire ne cesse de se placer entre le disque et moi pour m’empêcher de l’attraper. Il a le droit tant qu’il ne me touche pas. Il protège son disque.>

### ISSUE THREAD

**Issue by hippalectryon-0** [sallesma/timeout-ultimate#41]
```
{
    category: Categories.RECEIVER,
    question:
      'Le disque plane. Mon adversaire ne cesse de se placer entre le disque et moi pour m’empêcher de l’attraper. Il a le droit tant qu’il ne me touche pas. Il protège son disque.',
    image: undefined,
    answerChoices: {
      a: 'Vrai',
      b: 'Faux',
    },
    correctAnswers: ['b'],
    explanation:
      ' Quand le disque est en l’air, un joueur ne peut se déplacer de manière à uniquement empêcher un adversaire de prendre une trajectoire inoccupée vers le disque. Il fait obstruction aux déplacements de l’adversaire. Il y a donc une violation.',
    rules: ['12.5.1.'],
    source: 'Disque Tu Sais - Pablo',
    level: Levels.MIDDLE,
  },
```

Comme indiqué dans les annotations, *"Player positioning (12.5) (...) Note The key word in this rule is ‘solely’. The intent of the player’s movement can be partly motivated to prevent an opponent from taking an unoccupied path to the disc, so long as it is part of a general effort to make a play on the disc. If a trailing player runs into a player in front of them, it is nearly always a foul on the trailing player."*

La formulation de la question n'est pas claire sur le fait que le joueur impliqué ne fait aucun effort pour jouer le disque. Il me semble donc que la question n'est pas correcte dans sa formulation actuelle.

**Comment by sallesma** [comment]
Oui, ça vaut le coup de rajouter un "uniquement" dans la question, déjà présent dans l'explication.

Et note pour pas oublier : il y a une espace en trop au début de l'explication
