### ISSUE TITLE
Fix <Lors de mon replacement dans le stack, mon adversaire me fait un croche-pied involontaire. J’appelle faute et mon adversaire conteste. Il a tort.>

### ISSUE THREAD

**Issue by hippalectryon-0** [sallesma/timeout-ultimate#42]
```
{
    category: Categories.RECEIVER,
    question:
      'Lors de mon replacement dans le stack, mon adversaire me fait un croche-pied involontaire. J’appelle faute et mon adversaire conteste. Il a tort.',
    image: undefined,
    answerChoices: {
      a: 'Vrai',
      b: 'Faux',
    },
    correctAnswers: ['b'],
    explanation:
      "« Tous les joueurs doivent essayer d’éviter les contacts. Néanmoins un contact accidentel n’affectant pas le résultat d’une action ou la sécurité des joueurs n'est pas considéré comme une faute ». Il avait donc raison de contester car c’est moi qui n’aurait pas dû appeler la faute.",
    rules: ['12.8.'],
    source: 'Disque Tu Sais - Pablo',
    level: Levels.DIFFICULT,
  },
```

Cette question se fonde (il me semble) sur l'ancienne définition de "minor contact". Règle 12.8: *Some minor contact may occur as two or more players move towards a single point simultaneously. Minor contact should be minimized but is not considered a foul.*, où *minor contact: contact that involves minimal physical force and does not affect the movements or position of another player*. Il me semble qu'on est clairement pas dans ce cas ici, et qu'il est parfaitement justifié d'appeler une Indirect Foul.

**Comment by sallesma** [comment]
C'est vrai.

On peut corriger ça, et ça vaudrait le coup de rajouter une question avec un vrai contact mineur (genre un petit bump ou arm check)
