### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by bsneider** [sallesma/timeout-ultimate#47]
translate into English, will try to use http://deepl.com, which I am told by an ML specialist is the best in the field.
Will then commit a new branch wi the English translated question bank. If this works we can likely do the same to other lanugauges supported
<img width="707" alt="image" src="https://user-images.githubusercontent.com/54788551/185682410-2a6a3044-0209-48bd-afdd-8c0e7f1b2923.png">

**Comment by bsneider** [comment]
see https://github.com/sallesma/timeout-ultimate/pull/56

**Comment by sallesma** [comment]
I translated the hand signals hint in https://github.com/sallesma/timeout-ultimate/commit/e0d90a627809b47965147e2763354d28758200c0

We still have the dictionary and many questions to translate

**Comment by bsneider** [comment]
> I translated the hand signals hint in [e0d90a6](https://github.com/sallesma/timeout-ultimate/commit/e0d90a627809b47965147e2763354d28758200c0)
> 
> We still have the dictionary and many questions to translate

Nice! I'd release as is, and then re-release if we can translate more questions. Its quite labor intensive.

**Comment by sallesma** [comment]
@bsneider It took too much time (i had to find an iphone to be able to test the built app), but it is finally released

thanks again for the translation!

I guess we can now improve it by translating much more questions (80 in English vs 270 in French)

**Comment by sallesma** [comment]
Done via https://github.com/sallesma/timeout-ultimate/commit/30e9f8e54385e432ee555c2d1581560e8b0cbcde
