### ISSUE TITLE
app.json contient web mais n'a pas les bons requirements

### ISSUE THREAD

**Issue by hippalectryon-0** [sallesma/timeout-ultimate#51]
Dans app.json il y a une clé "web" qui signifie un build web possible, mais lorsqu'on essait de le build on a une erreur relative aux requirements. Je ne sait pas si c'est 1) que package.json n'est pas à jour où 2) que la clé "web" est un résidu d'Expo qu'il faut enlever.

**Comment by sallesma** [comment]
Hello, c'est surtout parce que la version web n'est pas configurée (et pas vraiment prévue)

Il manque toute la config de webpack et le déploiement.

J'ai pas trop l'intention de le faire pour l'instant

**Comment by sallesma** [comment]
Corrigé dans 731af44e0be83bcd496b5a01e09501fabaabb8d3
