### ISSUE TITLE
Add appendices and annotations

### ISSUE THREAD

**Issue by sallesma** [sallesma/timeout-ultimate#7]
- [x] Hand signals
- [x] Definitions
- [x] Annotations
- [x] Appendices
- [ ] Decision diagrams

**Comment by sallesma** [comment]
Waiting for french translations of these documents

**Comment by mmouterde** [comment]
@sallesma sais tu si c'est prévu ? qui gère la traduction ? la fédé ?

**Comment by sallesma** [comment]
Pour la règles, c'était un groupe de travail monté pour l'occasion je crois

Il y a quelques infos à la fin du document pdf : https://github.com/sallesma/timeout-ultimate/blob/main/assets/WFDF%20Rules%20of%20Ultimate%202021-2024%20-%20French.pdf

Pour les annotations, je ne sais pas si c'est prévu. ça pourrait être intéressant de proposer à la fédé de les aider à le faire, ou de contacter les gens qui l'ont fait pour les règles

**Comment by sallesma** [comment]
Je vais envoyer un mail à la fédé prochainement à ce sujet

Est-ce que ça t'intéresse d'être en copie ? (si oui je veux bien ton email)

**Comment by mmouterde** [comment]
Ca m'intéresse en effet ! 
J'ai fait une demande pour traduire le livre de la WFDF aussi mais ils font trainer les choses.

**Comment by sallesma** [comment]
Hello Martin,

J'ai vu dans ta réponse à Anthony que tu comptes proposer une traduction prochainement. De mon côté je n'aurai pas trop le temps (quand je peux je m'attèle surtout à améliorer le code de l'app et la qualité des questions).

Est-ce que tu as pu trouver du monde pour t'aider ? Est-ce que veux que je relaie un appel à contributions ? (avec les réseaux sociaux du PUC+Focus ça touche pas mal de monde)
Est-ce que tu as une idée du temps qu'il vous faudra pour avoir une première version complète ?

**Comment by mmouterde** [comment]
Salut Martin,

Oui je compte bien proposer une traduction.

Pas de soucis, si tu n’as pas de temps pour ça, chacun contribue comme il le peut/veut.😉 pour ma part je compte sur ton app et peut me rendre dispo pour tester et te faire des retours.

Pour le moment, j’ai des volontaires et nous n’avons pas encore commencé. on se cherche une organisation. Dès que nous aurons trouvé, en petit groupe, une méthode de travail, je te dirais pour élargir et regrouper d’autres volontaires.

Je ne saurais pas te donner de date de fin… ça viendra quand ça viendra 😅 comme pour l’open source bénévole. 

J’ai aussi vu avec la WFDF pour traduire leur ebook, mais on va commencer par les annotations/annexes. Je te tiens au courant de notre avancement.
 
A+

**Comment by hippalectryon-0** [comment]
Au cas où, j'ai setup un portail de traduction collaboratif pour mon appli, si ça peut vous être utile.. https://weblate.wfdfrules.com/projects/wfdf-rules-2021/wfdf-appendix/fr/

**Comment by mmouterde** [comment]
Intéressant ! merci @hippalectryon-0 Je ne connais pas du tout l'outil, je vais explorer.

@sallesma Au final pour les annotations, j'ai commencé ici https://github.com/mmouterde/regles-ultimate-fr/pull/18
Ca devrait être relativement rapide à faire.  Jete également un coup d'oeil au reste de ce repos, il y a probablement des interopérabilités à faire.

**Comment by sallesma** [comment]
Ca marche, dès que t'as un truc à peut près terminé, je pense que tu peux l'envoyer à Anthony Affilié pour validation de la fédé.

Et me l'envoyer pour intégration dans timeout ultimate (ou proposer une PR)

**Comment by hippalectryon-0** [comment]
Pour info: ne voyant pas d'évolutions ici, j'ai traduit les annotations moi-même. Vous pouvez les trouver ici https://weblate.wfdfrules.com/projects/wfdf-rules-2021/wfdf-rules/fr/.

La fédé m'a royalement ignoré la dernière fois que je les ai contactés, donc je ne leur ai pas envoyé.

Edit: continué sur https://github.com/mmouterde/regles-ultimate-fr/issues/26 pour ne pas polluer ici

**Comment by sallesma** [comment]
Hello,
J'ai pas trop d'avis sur le fond (la traduction produite), je pense que ça vaut le coup que vous vous mettiez d'accord sur les 2 ou 3 points divergents pour arriver à une version finale qui fasse consensus.

> La fédé m'a royalement ignoré la dernière fois que je les ai contactés, donc je ne leur ai pas envoyé.

En revanche là dessus je peux appuyer je pense. Mon mail précédent à Su avait trouvé réponse, et je pense que via les connexions PUC/Fédé on peut pousser une traduction pour la faire reconnaître comme "officielle" ce qui serait vraiment top

Je vous proposer un truc du genre :
1. Faites quelques aller-retours et PR pour converger vers une version satisfaisante pour tout le monde. Je pense que l'avis de la fédé là dessus sera : on veut que ce soit au plus proche de l'original et avec les mêmes choix de mots que dans les règles de base
2. On le fait relire par une des personnes qui avait traduit les règles de bases pour la fédé (les noms sont publics et on peut trouver les adresses via le PUC)
3. On renvoie à Su pour voir si on peut faire reconnaître la traduction comme "officielle"

Ça vous parait bien ?

**Comment by bsneider** [comment]
Appendix was added in English version, but not hooked up anywhere

**Comment by sallesma** [comment]
Appendix added to the app (in english)

I close this, since the only remaining task is now to translate the appendix to French (no official translation) and it is not directly related to this issue. Decision diagrams are not so important
